import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { Topnav } from "./_components/topnav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} h-screen flex-col overflow-hidden`}
      >
        <Topnav />
        {children}
      </body>
    </html>
  );
}
