/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uQ6sF3KXLJ7
 */
import { Button, type ButtonProps } from "~/components/ui/button";

export function XButton(props: ButtonProps) {
  return (
    <Button
      className="grid h-14 w-14 place-items-center rounded-full p-2 transition-colors duration-200 hover:bg-gray-100/40"
      variant="ghost"
      {...props}
    >
      <XIcon className="h-8 w-8 text-white" />
    </Button>
  );
}

function XIcon(props: { className?: string }) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
